name: Run .NET Selenium Tests (Parallel)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Debug

      - name: Set output path
        id: set_output
        run: echo "build_path=${{ github.workspace }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        chunk: [1, 2, 3, 4] # 4 parallel jobs
      fail-fast: false

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: 'Kundrakudi@95'
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SQL Server Command Line Tools
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/22.04/prod.list)"
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - run: sleep 15

      - name: Create & Seed DB
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kundrakudi@95' -Q "CREATE DATABASE CTMQA"
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kundrakudi@95' -d CTMQA -i scripts/sql/init.sql
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kundrakudi@95' -d CTMQA -i scripts/sql/data.sql

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Build project
        run: dotnet build --configuration Debug

      - name: Split Tests into Chunks
        run: |
          mkdir -p test_chunks
          dotnet test --list-tests > all_tests.txt || true
          grep -E "^[A-Za-z0-9_.]+$" all_tests.txt > clean_tests.txt
          split -n l/4 clean_tests.txt test_chunks/chunk_
          mv test_chunks/chunk_aa test_chunks/tests_1.txt
          mv test_chunks/chunk_ab test_chunks/tests_2.txt
          mv test_chunks/chunk_ac test_chunks/tests_3.txt
          mv test_chunks/chunk_ad test_chunks/tests_4.txt

      - name: Run Tests for Chunk ${{ matrix.chunk }}
        run: |
          echo "=== Running chunk ${{ matrix.chunk }} ==="
          TESTS=$(paste -sd '|' test_chunks/tests_${{ matrix.chunk }}.txt)
          dotnet test --no-build \
            --filter "FullyQualifiedName~$TESTS" \
            --logger:"trx;LogFileName=test_results_chunk_${{ matrix.chunk }}.trx" \
            --results-directory "TestResults"
        continue-on-error: true

      - name: Upload Allure Results (Raw)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AllureResults-${{ matrix.chunk }}
          path: TestResults
          retention-days: 1

  deploy:
    name: Merge Allure & Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          pattern: AllureResults-*
          merge-multiple: true
          path: TestResults

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Combined Allure Report
        run: allure generate TestResults --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
