# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run .NET Selenium Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Debug

      - name: Set output path
        id: set_output
        run: echo "build_path=${{ github.workspace }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Allure CLI (portable)
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Build project
        run: dotnet build --configuration Debug

      - name: Run NUnit Tests with Allure
        run: |
          dotnet test --no-build --logger:"trx;LogFileName=test_results.trx" --results-directory "TestResults" --verbosity normal

      - name: Generate Allure Results
        run: |
          allure generate TestResults --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AllureReport
          path: allure-report
          retention-days: 30

      - name: Upload Allure Results (Raw)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AllureResults
          path: TestResults
          retention-days: 30
